# Media configuration
media:
  input: assets/img/uploads
  output: /assets/img/uploads
  path: assets/img/uploads
  extensions: [jpg, jpeg, png, gif, svg]

# Content configuration
content:
  - name: posts
    label: Articles
    type: collection
    path: _posts
    icon: newspaper
    view:
      fields: [title, date, author, category]
      primary: title
      sort: [date, title]
      default:
        sort: date
        order: desc
    fields:
      - name: title
        label: Titre
        type: string
        required: true
      - name: date
        label: Date de publication
        type: date
        required: true
      - name: author
        label: Auteur
        type: string
        required: true
      - name: category
        label: Rubrique
        type: select
        options:
          values: [actu, conseils, coup-de-gueule, critiques, discussions, edito]
      - name: tags
        label: Tags
        type: string
        list: true
      - name: image
        label: Image de couverture
        type: image
      - name: description
        label: Synopsis
        type: string
      - name: body
        label: Contenu
        type: rich-text

  - name: pages
    label: Pages
    type: collection
    icon: layers
    path: pages
    view:
      fields: [title, description]
    fields:
      - name: title
        label: Titre
        type: string
        required: true
      - name: description
        label: Description
        type: string
      - name: body
        label: Contenu
        type: rich-text

  - name: authors
    label: Rédacteurs
    type: collection
    icon: square-user
    path: _authors
    fields:
      - name: name
        label: Layout
        type: string
        default: author
        hidden: True
      - name: name
        label: Pseudonyme
        type: string
        required: true
      - name: display_name
        label: Nom complet
        type: string
        required: true
      - name: position
        label: Role
        type: string
      - name: name
        label: Pseudo Twitter
        type: string
      - name: name
        label: Pseudo Github
        type: string
      - name: name
        label: Pseudo Facebook
        type: string
      - name: name
        label: Pseudo Instagram
        type: string
      - name: name
        label: Pseudo LinkedIn
        type: string
      - name: name
        label: Pseudo Medium
        type: string
      - name: name
        label: Pseudo Threads
        type: string
      - name: name
        label: Pseudo Letterboxd
        type: string
      - name: name
        label: Pseudo MyAnimeList
        type: string
      - name: bio
        label: Biographie
        type: text
      - name: avatar
        label: Avatar
        type: image