# Site Settings
#=include site.yml

# Social Media Settings
# Remove the item if you don't need it
#=include social.yml

# Posts Settings
#=include posts.yml

# Advanced Settings
#=include advanced.yml

# Localization
#=include translations.yml

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/
collections:
  authors:
    output: true
show_get_theme_btn: false
use_logo: true

############################################################
# Site configuration for the Jekyll 3 Pagination Gem
# The values here represent the defaults if nothing is set
pagination:
  enabled: true
  debug: false
  collection: 'posts'
  per_page: 8
  permalink: '/page/:num/'
  # Optional, the default locale to use, omit to disable (depends on a field 'locale' to be specified in the posts, 
  # in reality this can be any value, suggested are the Microsoft locale-codes (e.g. en_US, en_GB) or simply the ISO-639 language code )
  locale: 'fr_FR' 

# SASS
sass:
  style: compressed

# Plugins
plugins:
  - jekyll-paginate-v2
  - liquid_reading_time

# Exclude my node related stuff
exclude: [
  'package.json',
  'package-lock.json',
  'src',
  'node_modules',
  'initpost.sh',
  'Gemfile',
  'Gemfile.lock',
  'gulpfile.js',
  'README.md'
]

# Theme
version: v3.1.2

# Tags
autopages:
  enabled: true
  collections:
      enabled: false
  categories:
      enabled: false
  tags: 
    layouts: 
      - autopage_tags.html
    title: 'Articles sur le thème ":tag"' # :tag is replaced by the tag name
    permalink: '/tags/:tag'
    silent: false
    slugify:
      mode: 'default'   # :tag is slugified.
      case: false
