date_format: "%d %B %Y"
formspree_form_id: mqknkwel
name: Le 7EPTIEME ŒIL
title: Le 7EPTIEME ŒIL| L'œil qui voit tout le Cinéma
language: fr
description: "L'oeil qui voit tout le Cinéma "
tags:
  - blog
  - cinema
  - critique
show_hero: true
menu:
  - title: Accueil
    url: /
  - title: Notre équipe
    url: /staff
  - title: À Propos
    url: /about
  - title: Nous contacter
    url: /contact
email: le7eptiemeoeil@gmail.com
