date_format: "%d %B %Y"
formspree_form_id: mqknkwel
name: Le 7EPTIEME ŒIL
title: Le 7EPTIEME ŒIL| L'œil qui voit tout le Cinéma
language: fr
description: Le 7EPTIEME ŒIL est un site web ivoirien dévolu aux critiques et
  aux informations sur le cinéma. Il est le fruit de quatre ivoiriens passionnés
  par cet art et ayant le désir de le faire connaître sous divers angles. Pour
  ce faire, différentes thématiques seront abordées pour vous faire découvrir
  l'histoire et l'actualité du cinéma local et international (les sorties, les
  évènements, etc).  Le 7EPTIEME ŒIL vous fera voir tout le cinéma.
tags:
  - blog
  - cinema
  - critique
show_hero: true
menu:
  - title: Accueil
    url: /
  - title: Notre équipe
    url: /staff
  - title: À Propos
    url: /about
  - title: Nous contacter
    url: /contact
email: le7eptiemeoeil@gmail.com
