date_format: "%d %B %Y"
formspree_form_id: mqknkwel
name: Le 7eptième Œil
title: Le 7eptième Œil | L'œil qui voit tout le Cinéma
language: fr
description: Site web ivoirien dédié aux critiques et aux informations sur le cinéma. Retrouvez l'actualité du cinéma local et international, des décryptages et analyses...
tags:
  - blog
  - cinema
  - critique
show_hero: true
hero_categories: "edito,conseils,coup-de-gueule,critiques,discussions"
menu:
  - title: Accueil
    url: /
  - title: Notre équipe
    url: /staff
  - title: À Propos
    url: /about
  - title: Nous contacter
    url: /contact
email: le7eptiemeoeil@gmail.com
